package db

import (
	"context"
	"fmt"
	"log"

	"bbflow-server/config"

	"github.com/jackc/pgx/v5/pgxpool"
)

var Pool *pgxpool.Pool

func Init() error {
	cfg := config.AppConfig.DB
	connStr := fmt.Sprintf("postgres://%s:%s@%s:%d/%s",
		cfg.User, cfg.Password, cfg.Host, cfg.Port, cfg.Database)

	var err error
	Pool, err = pgxpool.New(context.Background(), connStr)
	if err != nil {
		return fmt.Errorf("unable to connect to database: %w", err)
	}

	if err := Pool.Ping(context.Background()); err != nil {
		return fmt.Errorf("unable to ping database: %w", err)
	}

	log.Println("Connected to PostgreSQL database")

	if err := initTables(); err != nil {
		return err
	}

	return nil
}

func initTables() error {
	ctx := context.Background()

	// Users table
	_, err := Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS users (
			id SERIAL PRIMARY KEY,
			openid TEXT UNIQUE NOT NULL,
			nickname TEXT,
			avatar_url TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create users table: %w", err)
	}

	// Blood pressure records table
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS bp_records (
			id SERIAL PRIMARY KEY,
			user_id TEXT NOT NULL,
			systolic INTEGER NOT NULL,
			diastolic INTEGER NOT NULL,
			heart_rate INTEGER,
			measured_at TIMESTAMP NOT NULL,
			tags TEXT,
			note TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			FOREIGN KEY(user_id) REFERENCES users(openid)
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create bp_records table: %w", err)
	}

	// OCR logs table
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS ocr_logs (
			id SERIAL PRIMARY KEY,
			user_id TEXT NOT NULL,
			image_path TEXT,
			raw_result TEXT,
			parsed_result TEXT,
			status TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			FOREIGN KEY(user_id) REFERENCES users(openid)
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create ocr_logs table: %w", err)
	}

	// Feedbacks / feature requests table
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS feedbacks (
			id SERIAL PRIMARY KEY,
			user_id TEXT NOT NULL,
			type TEXT NOT NULL,
			content TEXT NOT NULL,
			contact TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			FOREIGN KEY(user_id) REFERENCES users(openid)
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create feedbacks table: %w", err)
	}

	// Authorization codes table (dynamically generated by admin)
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS auth_codes (
			id SERIAL PRIMARY KEY,
			code TEXT UNIQUE NOT NULL,
			data_quota INTEGER DEFAULT 10000,
			ocr_quota INTEGER DEFAULT 10000,
			duration_days INTEGER DEFAULT 365,
			used_by TEXT,
			used_at TIMESTAMP,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create auth_codes table: %w", err)
	}

	// Share tokens table
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS share_tokens (
			token TEXT PRIMARY KEY,
			user_id TEXT NOT NULL,
			time_range TEXT NOT NULL,
			share_future_data BOOLEAN DEFAULT FALSE,
			expires_at TIMESTAMP NOT NULL,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			FOREIGN KEY(user_id) REFERENCES users(openid)
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create share_tokens table: %w", err)
	}

	// Add rate_limit_config column
	_, err = Pool.Exec(ctx, `
		ALTER TABLE users 
		ADD COLUMN IF NOT EXISTS rate_limit_config JSONB DEFAULT '{}';
	`)
	if err != nil {
		return fmt.Errorf("failed to add rate_limit_config column: %w", err)
	}

	// Add is_admin column
	_, err = Pool.Exec(ctx, `
		ALTER TABLE users 
		ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT FALSE;
	`)
	if err != nil {
		return fmt.Errorf("failed to add is_admin column: %w", err)
	}

	// Add referrer_id column (推荐人)
	_, err = Pool.Exec(ctx, `
		ALTER TABLE users 
		ADD COLUMN IF NOT EXISTS referrer_id TEXT;
	`)
	if err != nil {
		return fmt.Errorf("failed to add referrer_id column: %w", err)
	}

	// Add referral_code column (用户自己的推荐码)
	_, err = Pool.Exec(ctx, `
		ALTER TABLE users 
		ADD COLUMN IF NOT EXISTS referral_code TEXT UNIQUE;
	`)
	if err != nil {
		return fmt.Errorf("failed to add referral_code column: %w", err)
	}

	log.Println("Database initialized successfully")
	return nil
}

func Close() {
	if Pool != nil {
		Pool.Close()
	}
}
