package db

import (
	"context"
	"fmt"
	"log/slog"

	"bbflow-server/config"

	"github.com/jackc/pgx/v5/pgxpool"
)

var Pool *pgxpool.Pool

func Init() error {
	cfg := config.AppConfig.DB
	connStr := fmt.Sprintf("postgres://%s:%s@%s:%d/%s",
		cfg.User, cfg.Password, cfg.Host, cfg.Port, cfg.Database)

	var err error
	Pool, err = pgxpool.New(context.Background(), connStr)
	if err != nil {
		return fmt.Errorf("unable to connect to database: %w", err)
	}

	if err := Pool.Ping(context.Background()); err != nil {
		return fmt.Errorf("unable to ping database: %w", err)
	}

	slog.Info("connected to database")

	if err := initTables(); err != nil {
		return err
	}

	return nil
}

func initTables() error {
	ctx := context.Background()

	// Users table
	_, err := Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS users (
			id SERIAL PRIMARY KEY,
			openid TEXT UNIQUE NOT NULL,
			nickname TEXT,
			avatar_url TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create users table: %w", err)
	}

	// Blood pressure records table
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS bp_records (
			id SERIAL PRIMARY KEY,
			user_id TEXT NOT NULL,
			systolic INTEGER NOT NULL,
			diastolic INTEGER NOT NULL,
			heart_rate INTEGER,
			measured_at TIMESTAMP NOT NULL,
			tags TEXT,
			note TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			FOREIGN KEY(user_id) REFERENCES users(openid)
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create bp_records table: %w", err)
	}

	// OCR logs table
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS ocr_logs (
			id SERIAL PRIMARY KEY,
			user_id TEXT NOT NULL,
			image_path TEXT,
			raw_result TEXT,
			parsed_result TEXT,
			status TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			FOREIGN KEY(user_id) REFERENCES users(openid)
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create ocr_logs table: %w", err)
	}

	// Feedbacks / feature requests table
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS feedbacks (
			id SERIAL PRIMARY KEY,
			user_id TEXT NOT NULL,
			type TEXT NOT NULL,
			content TEXT NOT NULL,
			contact TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			FOREIGN KEY(user_id) REFERENCES users(openid)
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create feedbacks table: %w", err)
	}

	// Activation links table (generated by admin, used to activate paid users)
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS activation_links (
			id SERIAL PRIMARY KEY,
			code TEXT UNIQUE NOT NULL,
			duration_days INTEGER DEFAULT 365,
			max_invite_links INTEGER DEFAULT 5,
			used_by TEXT,
			used_at TIMESTAMP,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create activation_links table: %w", err)
	}

	// Invite links table (created by paid users, used by invitees)
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS invite_links (
			id SERIAL PRIMARY KEY,
			code TEXT UNIQUE NOT NULL,
			creator_id TEXT NOT NULL,
			used_by TEXT,
			used_at TIMESTAMP,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			FOREIGN KEY(creator_id) REFERENCES users(openid)
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create invite_links table: %w", err)
	}

	// Share tokens table
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS share_tokens (
			token TEXT PRIMARY KEY,
			user_id TEXT NOT NULL,
			time_range TEXT NOT NULL,
			share_future_data BOOLEAN DEFAULT FALSE,
			expires_at TIMESTAMP NOT NULL,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			FOREIGN KEY(user_id) REFERENCES users(openid)
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create share_tokens table: %w", err)
	}

	// Add rate_limit_config column (legacy, kept for migration)
	_, err = Pool.Exec(ctx, `
		ALTER TABLE users 
		ADD COLUMN IF NOT EXISTS rate_limit_config JSONB DEFAULT '{}';
	`)
	if err != nil {
		return fmt.Errorf("failed to add rate_limit_config column: %w", err)
	}

	// Add is_admin column
	_, err = Pool.Exec(ctx, `
		ALTER TABLE users 
		ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT FALSE;
	`)
	if err != nil {
		return fmt.Errorf("failed to add is_admin column: %w", err)
	}

	// Add paid_until column (null = free user)
	_, err = Pool.Exec(ctx, `
		ALTER TABLE users 
		ADD COLUMN IF NOT EXISTS paid_until TIMESTAMP;
	`)
	if err != nil {
		return fmt.Errorf("failed to add paid_until column: %w", err)
	}

	// Add sponsor_id column (the paid user who invited this user)
	_, err = Pool.Exec(ctx, `
		ALTER TABLE users 
		ADD COLUMN IF NOT EXISTS sponsor_id TEXT;
	`)
	if err != nil {
		return fmt.Errorf("failed to add sponsor_id column: %w", err)
	}

	// Add max_invite_links column (how many invite links the user can create)
	_, err = Pool.Exec(ctx, `
		ALTER TABLE users 
		ADD COLUMN IF NOT EXISTS max_invite_links INTEGER DEFAULT 0;
	`)
	if err != nil {
		return fmt.Errorf("failed to add max_invite_links column: %w", err)
	}

	// Migrate legacy authorized users to new paid_until system
	_, err = Pool.Exec(ctx, `
		UPDATE users 
		SET paid_until = (rate_limit_config->>'expires_at')::timestamp,
		    max_invite_links = 5
		WHERE rate_limit_config->>'authorized' = 'true'
		  AND paid_until IS NULL
		  AND rate_limit_config->>'expires_at' IS NOT NULL;
	`)
	if err != nil {
		// Non-fatal migration error, log and continue
		slog.Warn("failed to migrate legacy users", "error", err)
	}

	// --- OCR reliability columns ---
	for _, col := range []struct{ name, def string }{
		{"record_id", "INTEGER"},
		{"final_result", "TEXT"},
		{"confidence_score", "REAL"},
		{"extraction_strategy", "TEXT"},
		{"verification_status", "TEXT DEFAULT 'auto_accepted'"},
		{"user_corrected_values", "JSONB"},
	} {
		_, err = Pool.Exec(ctx, fmt.Sprintf(
			`ALTER TABLE ocr_logs ADD COLUMN IF NOT EXISTS %s %s`, col.name, col.def))
		if err != nil {
			slog.Warn("failed to add ocr_logs column", "column", col.name, "error", err)
		}
	}

	// --- Share security columns ---
	for _, col := range []struct{ name, def string }{
		{"is_revoked", "BOOLEAN DEFAULT FALSE"},
		{"revoked_at", "TIMESTAMP"},
		{"access_count", "INTEGER DEFAULT 0"},
		{"last_accessed_at", "TIMESTAMP"},
	} {
		_, err = Pool.Exec(ctx, fmt.Sprintf(
			`ALTER TABLE share_tokens ADD COLUMN IF NOT EXISTS %s %s`, col.name, col.def))
		if err != nil {
			slog.Warn("failed to add share_tokens column", "column", col.name, "error", err)
		}
	}

	// --- Share access audit log ---
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS share_access_logs (
			id SERIAL PRIMARY KEY,
			token TEXT NOT NULL,
			accessor_ip TEXT,
			user_agent TEXT,
			accessed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create share_access_logs table: %w", err)
	}

	// --- Medications table ---
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS medications (
			id SERIAL PRIMARY KEY,
			user_id TEXT NOT NULL,
			name TEXT NOT NULL,
			dosage TEXT,
			frequency TEXT,
			reminder_time TEXT,
			is_active BOOLEAN DEFAULT TRUE,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			FOREIGN KEY(user_id) REFERENCES users(openid)
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create medications table: %w", err)
	}

	// --- Medication logs table ---
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS medication_logs (
			id SERIAL PRIMARY KEY,
			medication_id INTEGER NOT NULL,
			user_id TEXT NOT NULL,
			taken_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			skipped BOOLEAN DEFAULT FALSE,
			note TEXT,
			FOREIGN KEY(medication_id) REFERENCES medications(id),
			FOREIGN KEY(user_id) REFERENCES users(openid)
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create medication_logs table: %w", err)
	}

	// --- Support tickets table ---
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS support_tickets (
			id SERIAL PRIMARY KEY,
			user_id TEXT NOT NULL,
			subject TEXT NOT NULL,
			status TEXT DEFAULT 'open',
			priority TEXT DEFAULT 'normal',
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			FOREIGN KEY(user_id) REFERENCES users(openid)
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create support_tickets table: %w", err)
	}

	// --- Support ticket messages ---
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS ticket_messages (
			id SERIAL PRIMARY KEY,
			ticket_id INTEGER NOT NULL,
			sender_type TEXT NOT NULL,
			content TEXT NOT NULL,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			FOREIGN KEY(ticket_id) REFERENCES support_tickets(id)
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create ticket_messages table: %w", err)
	}

	// --- Analytics events ---
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS analytics_events (
			id SERIAL PRIMARY KEY,
			user_id TEXT,
			event_type TEXT NOT NULL,
			event_data JSONB,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create analytics_events table: %w", err)
	}

	// --- Data export requests ---
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS data_exports (
			id SERIAL PRIMARY KEY,
			user_id TEXT NOT NULL,
			format TEXT NOT NULL DEFAULT 'json',
			status TEXT DEFAULT 'pending',
			file_path TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			completed_at TIMESTAMP,
			FOREIGN KEY(user_id) REFERENCES users(openid)
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create data_exports table: %w", err)
	}

	// --- Idempotency keys ---
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS idempotency_keys (
			key TEXT PRIMARY KEY,
			user_id TEXT NOT NULL,
			response_status INTEGER,
			response_body TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create idempotency_keys table: %w", err)
	}

	slog.Info("database initialized successfully")

	// --- Payment & subscription tables ---
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS plans (
			id SERIAL PRIMARY KEY,
			name TEXT NOT NULL,
			description TEXT DEFAULT '',
			price_cents INTEGER NOT NULL,
			duration_days INTEGER NOT NULL DEFAULT 365,
			max_records INTEGER NOT NULL DEFAULT -1,
			features TEXT DEFAULT '{}',
			is_active BOOLEAN DEFAULT true,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create plans table: %w", err)
	}

	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS payment_orders (
			id SERIAL PRIMARY KEY,
			user_id INTEGER NOT NULL,
			plan_id INTEGER NOT NULL REFERENCES plans(id),
			order_no TEXT UNIQUE NOT NULL,
			amount_cents INTEGER NOT NULL,
			status TEXT NOT NULL DEFAULT 'pending',
			trade_no TEXT,
			payment_method TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			paid_at TIMESTAMP
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create payment_orders table: %w", err)
	}

	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS subscriptions (
			id SERIAL PRIMARY KEY,
			user_id INTEGER NOT NULL,
			plan_id INTEGER NOT NULL REFERENCES plans(id),
			order_id INTEGER REFERENCES payment_orders(id),
			starts_at TIMESTAMP NOT NULL,
			expires_at TIMESTAMP NOT NULL,
			status TEXT NOT NULL DEFAULT 'active',
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create subscriptions table: %w", err)
	}

	// Insert default plans if none exist
	var planCount int
	err = Pool.QueryRow(ctx, `SELECT COUNT(*) FROM plans`).Scan(&planCount)
	if err == nil && planCount == 0 {
		_, _ = Pool.Exec(ctx, `
			INSERT INTO plans (name, description, price_cents, duration_days, max_records, features) VALUES
			('月度会员', '按月订阅，无限血压记录', 990, 30, -1, '{"unlimited_records": true, "insights": true, "export": true}'),
			('年度会员', '年度订阅，性价比最高', 6800, 365, -1, '{"unlimited_records": true, "insights": true, "export": true, "priority_support": true}'),
			('终身会员', '一次购买，永久使用', 12800, 36500, -1, '{"unlimited_records": true, "insights": true, "export": true, "priority_support": true, "lifetime": true}')
		`)
		slog.Info("default plans seeded")
	}

	// Reminder preference + dispatch log
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS reminder_prefs (
			user_id TEXT PRIMARY KEY REFERENCES users(openid),
			med_reminders_enabled BOOLEAN DEFAULT FALSE,
			measure_reminders_enabled BOOLEAN DEFAULT FALSE,
			measure_reminder_time TEXT DEFAULT '08:00',
			updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create reminder_prefs table: %w", err)
	}

	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS reminder_dispatches (
			id SERIAL PRIMARY KEY,
			user_id TEXT NOT NULL,
			medication_id INTEGER,
			reminder_type TEXT NOT NULL,
			dispatch_date DATE NOT NULL,
			dispatch_minute TEXT NOT NULL,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			UNIQUE(user_id, medication_id, reminder_type, dispatch_date, dispatch_minute)
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create reminder_dispatches table: %w", err)
	}

	_, _ = Pool.Exec(ctx, `ALTER TABLE bp_records ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP`)

	slog.Info("all tables initialized")
	return nil
}

func Close() {
	if Pool != nil {
		Pool.Close()
	}
}
