package db

import (
	"context"
	"fmt"
	"log/slog"

	"bbflow-server/config"

	"github.com/jackc/pgx/v5/pgxpool"
)

var Pool *pgxpool.Pool

func Init() error {
	cfg := config.AppConfig.DB
	connStr := fmt.Sprintf("postgres://%s:%s@%s:%d/%s",
		cfg.User, cfg.Password, cfg.Host, cfg.Port, cfg.Database)

	var err error
	Pool, err = pgxpool.New(context.Background(), connStr)
	if err != nil {
		return fmt.Errorf("unable to connect to database: %w", err)
	}

	if err := Pool.Ping(context.Background()); err != nil {
		return fmt.Errorf("unable to ping database: %w", err)
	}

	slog.Info("connected to database")

	if err := initTables(); err != nil {
		return err
	}

	return nil
}

func initTables() error {
	ctx := context.Background()

	// Users table
	_, err := Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS users (
			id SERIAL PRIMARY KEY,
			openid TEXT UNIQUE NOT NULL,
			nickname TEXT,
			avatar_url TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create users table: %w", err)
	}

	// Blood pressure records table
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS bp_records (
			id SERIAL PRIMARY KEY,
			user_id TEXT NOT NULL,
			systolic INTEGER NOT NULL,
			diastolic INTEGER NOT NULL,
			heart_rate INTEGER,
			measured_at TIMESTAMP NOT NULL,
			tags TEXT,
			note TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			FOREIGN KEY(user_id) REFERENCES users(openid)
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create bp_records table: %w", err)
	}

	// OCR logs table
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS ocr_logs (
			id SERIAL PRIMARY KEY,
			user_id TEXT NOT NULL,
			image_path TEXT,
			raw_result TEXT,
			parsed_result TEXT,
			status TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			FOREIGN KEY(user_id) REFERENCES users(openid)
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create ocr_logs table: %w", err)
	}

	// Feedbacks / feature requests table
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS feedbacks (
			id SERIAL PRIMARY KEY,
			user_id TEXT NOT NULL,
			type TEXT NOT NULL,
			content TEXT NOT NULL,
			contact TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			FOREIGN KEY(user_id) REFERENCES users(openid)
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create feedbacks table: %w", err)
	}

	// Activation links table (generated by admin, used to activate paid users)
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS activation_links (
			id SERIAL PRIMARY KEY,
			code TEXT UNIQUE NOT NULL,
			duration_days INTEGER DEFAULT 365,
			max_invite_links INTEGER DEFAULT 5,
			used_by TEXT,
			used_at TIMESTAMP,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create activation_links table: %w", err)
	}

	// Invite links table (created by paid users, used by invitees)
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS invite_links (
			id SERIAL PRIMARY KEY,
			code TEXT UNIQUE NOT NULL,
			creator_id TEXT NOT NULL,
			used_by TEXT,
			used_at TIMESTAMP,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			FOREIGN KEY(creator_id) REFERENCES users(openid)
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create invite_links table: %w", err)
	}

	// Share tokens table
	_, err = Pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS share_tokens (
			token TEXT PRIMARY KEY,
			user_id TEXT NOT NULL,
			time_range TEXT NOT NULL,
			share_future_data BOOLEAN DEFAULT FALSE,
			expires_at TIMESTAMP NOT NULL,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			FOREIGN KEY(user_id) REFERENCES users(openid)
		);
	`)
	if err != nil {
		return fmt.Errorf("failed to create share_tokens table: %w", err)
	}

	// Add rate_limit_config column (legacy, kept for migration)
	_, err = Pool.Exec(ctx, `
		ALTER TABLE users 
		ADD COLUMN IF NOT EXISTS rate_limit_config JSONB DEFAULT '{}';
	`)
	if err != nil {
		return fmt.Errorf("failed to add rate_limit_config column: %w", err)
	}

	// Add is_admin column
	_, err = Pool.Exec(ctx, `
		ALTER TABLE users 
		ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT FALSE;
	`)
	if err != nil {
		return fmt.Errorf("failed to add is_admin column: %w", err)
	}

	// Add paid_until column (null = free user)
	_, err = Pool.Exec(ctx, `
		ALTER TABLE users 
		ADD COLUMN IF NOT EXISTS paid_until TIMESTAMP;
	`)
	if err != nil {
		return fmt.Errorf("failed to add paid_until column: %w", err)
	}

	// Add sponsor_id column (the paid user who invited this user)
	_, err = Pool.Exec(ctx, `
		ALTER TABLE users 
		ADD COLUMN IF NOT EXISTS sponsor_id TEXT;
	`)
	if err != nil {
		return fmt.Errorf("failed to add sponsor_id column: %w", err)
	}

	// Add max_invite_links column (how many invite links the user can create)
	_, err = Pool.Exec(ctx, `
		ALTER TABLE users 
		ADD COLUMN IF NOT EXISTS max_invite_links INTEGER DEFAULT 0;
	`)
	if err != nil {
		return fmt.Errorf("failed to add max_invite_links column: %w", err)
	}

	// Migrate legacy authorized users to new paid_until system
	_, err = Pool.Exec(ctx, `
		UPDATE users 
		SET paid_until = (rate_limit_config->>'expires_at')::timestamp,
		    max_invite_links = 5
		WHERE rate_limit_config->>'authorized' = 'true'
		  AND paid_until IS NULL
		  AND rate_limit_config->>'expires_at' IS NOT NULL;
	`)
	if err != nil {
		// Non-fatal migration error, log and continue
		slog.Warn("failed to migrate legacy users", "error", err)
	}

	slog.Info("database initialized successfully")
	return nil
}

func Close() {
	if Pool != nil {
		Pool.Close()
	}
}
